# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS  := 05_kern 
USER_TARGETS := 05_user
USER_LIBS  := -lz
LIBBPF_DIR = ../../libbpf/src
COMMON_DIR = ../common

include $(COMMON_DIR)/common.mk
